package alpvax.racemod.core;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.Mod.Metadata;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.versioning.ArtifactVersion;
import net.minecraftforge.fml.common.versioning.DefaultArtifactVersion;
import alpvax.playerpowers.api.PlayerPowersConstants;


@Mod(modid = RMConstants.MOD_ID)
public class RaceMod
{
	@Instance(RMConstants.MOD_ID)
	public static RaceMod instance;

	@Metadata(RMConstants.MOD_ID)
	public static ModMetadata meta;

	@EventHandler
	public void preInit(FMLPreInitializationEvent e)
	{
		meta.name = RMConstants.MOD_NAME;
		meta.version = RMConstants.MOD_VERSION;
		meta.description = "A mod to allow players to pick a race to play as, each of which grant certain perks and disadvantages";
		ArtifactVersion av = new DefaultArtifactVersion(PlayerPowersConstants.MOD_ID, true);//Unbounded
		meta.requiredMods.add(av);//Required
		meta.dependencies.add(av);//After
		meta.authorList.add("Alpvax");
		meta.credits = "Initial idea as a class mod by Alpvax, DevilHyena, Mr_Chaire and LordPeasant";
		meta.autogenerated = false;
	}
}